version: "3.4"
services:
  db:
    image: mariadb
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    healthcheck:
      test: [ 'CMD-SHELL', 'healthcheck.sh --su-mysql --connect --innodb_initialized' ]
      interval: 3s
      retries: 5
      start_period: 30s
      timeout: 30s
    environment:
      MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app_net
    ports:
      - "3306:3306"
    env_file:
      - ./.env
  filler:
    image: python-filler
    volumes:
      - ./data.csv:/src/filler/data.csv
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_net


  adminer:
    image: adminer
    restart: always
    ports:
      - "80:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_net
volumes:
  db-data:
networks:
  app_net:



